### ISSUE TITLE
Remove link to wedding website (since it's expired)

### ISSUE THREAD

**Issue by jcsrb** [martellaj/martellaj.github.io#1]
![untitled screencast 5](https://cloud.githubusercontent.com/assets/119011/16681806/8aa53820-44ff-11e6-84ff-da8aff185ca2.gif)

**Comment by martellaj** [comment]
Thanks for the report! I haven't made time to update my personal website in a while (recently transitioned to a new job and had a wedding coming up). Job transition has gone pretty well and I got married 2 weeks ago... time to update this thing. Thanks, @jcsrb!

**Comment by jcsrb** [comment]
@martellaj congrats on both ! :tada:

**Comment by martellaj** [comment]
Closed in 668117e310dc4822eaac402b8b57cbd0d5753ed5.
